dist: trusty
git:
  # use depth 5 to leave enough room for concurrent builds
  depth: 5
language: ruby
cache: bundler
bundler_args: --path=.bundle/gems --jobs=3 --retry=3 --without=docs
rvm:
- &release_ruby 2.7.0
- 2.6.5
- 2.5.7
- 2.4.9
- &oldest_ruby 2.3.8
matrix:
  include:
  - rvm: jruby-9.2.9.0
    env: JRUBY_OPTS='--dev'
  - rvm: jruby-9.1.17.0
    env: JRUBY_OPTS='--dev'
  - rvm: *oldest_ruby
    env: ASCIIDOCTOR_VERSION=1.5.3
env:
  global:
  # use system libraries to speed up installation of nokogiri
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script:
- bundle exec ruby -w $(bundle exec ruby -e "print Gem.bin_path 'rake', 'rake'") spec
deploy:
  provider: rubygems
  gem: asciidoctor-epub3
  api_key: ${RUBYGEMS_API_KEY}
  on:
    tags: true
    repo: asciidoctor/asciidoctor-epub3
    rvm: *release_ruby
